# Generated by Django 5.2.15 on 2026-06-22 04:21

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Merchant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="상호")),
                (
                    "industry",
                    models.CharField(
                        choices=[
                            ("food", "외식/음식점"),
                            ("beauty", "미용/뷰티"),
                            ("retail", "소매/판매"),
                            ("cafe", "카페/디저트"),
                            ("service", "생활서비스"),
                            ("etc", "기타"),
                        ],
                        max_length=20,
                        verbose_name="업종",
                    ),
                ),
                (
                    "sub_category",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="예: 고깃집, 네일샵 — 코퍼스/벤치마크 라우팅",
                        max_length=100,
                        verbose_name="세부 카테고리",
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        help_text="동/역세권/배후 — [M1] 물리적 가용성",
                        max_length=200,
                        verbose_name="위치·상권",
                    ),
                ),
                (
                    "monthly_revenue",
                    models.PositiveBigIntegerField(
                        blank=True,
                        help_text="KPI 트리 분모. 미확보 시 추정(D).",
                        null=True,
                        verbose_name="월 매출(최근 3개월 평균, 원)",
                    ),
                ),
                (
                    "capacity",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="추정모델 상한",
                        null=True,
                        verbose_name="좌석/객수 캐파",
                    ),
                ),
                (
                    "business_days_per_week",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(7),
                        ],
                        verbose_name="주 영업일",
                    ),
                ),
                (
                    "channels",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='예: ["naver_place","instagram","baemin"] — 연동 후보',
                        verbose_name="운영 채널",
                    ),
                ),
                (
                    "growth_goal_pct",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="예: 15.0 → 3개월 +15%",
                        max_digits=5,
                        null=True,
                        verbose_name="90일 목표 성장률(%)",
                    ),
                ),
                (
                    "consent_data_processing",
                    models.BooleanField(
                        default=False,
                        help_text="intake §4 개인정보 게이트. 미동의 시 거래로그 수집 불가.",
                        verbose_name="고객데이터 위탁처리 동의",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정"),
                ),
            ],
            options={
                "verbose_name": "소상공인 업체",
                "verbose_name_plural": "소상공인 업체",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ConversionBaseline",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "aov",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="매출/객수",
                        null=True,
                        verbose_name="객단가 AOV(원)",
                    ),
                ),
                (
                    "visit_to_purchase_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="[M12] 반별점↑→매진 49%↑",
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="방문→구매 전환율(%)",
                    ),
                ),
                (
                    "current_offer",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="[M4] 손실프레임 / [M5] 가격끝자리",
                        max_length=300,
                        verbose_name="현재 오퍼·가격구조",
                    ),
                ),
                (
                    "negative_review_monthly",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="[M13] 부정리뷰가 더 무겁다 → 신속대응",
                        null=True,
                        verbose_name="월 부정리뷰 수",
                    ),
                ),
                (
                    "data_grade",
                    models.CharField(
                        choices=[
                            ("A", "A 연동(POS·플레이스 API)"),
                            ("B", "B 내보내기(엑셀·정산서)"),
                            ("C", "C 수기(사장님 입력)"),
                            ("D", "D 추정(업종평균·모델)"),
                        ],
                        default="C",
                        max_length=1,
                        verbose_name="데이터 등급",
                    ),
                ),
                (
                    "merchant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conversion",
                        to="onboarding.merchant",
                        verbose_name="업체",
                    ),
                ),
            ],
            options={
                "verbose_name": "전환 베이스라인",
                "verbose_name_plural": "전환 베이스라인",
            },
        ),
        migrations.CreateModel(
            name="AcquisitionBaseline",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "place_impressions",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="[M1] 가용성",
                        null=True,
                        verbose_name="네이버 플레이스 노출수(월)",
                    ),
                ),
                (
                    "place_clicks",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="유입 proxy",
                        null=True,
                        verbose_name="플레이스 클릭(월)",
                    ),
                ),
                (
                    "place_directions",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="길찾기(월)"
                    ),
                ),
                (
                    "place_calls",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="전화 연결(월)"
                    ),
                ),
                (
                    "review_count",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="[M11][M15]",
                        null=True,
                        verbose_name="리뷰 개수(채널 합)",
                    ),
                ),
                (
                    "avg_rating",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="0~5. [M11] 평점 1↑→매출 5~9%↑(독립업체)",
                        max_digits=2,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="평균 평점",
                    ),
                ),
                (
                    "new_visitor_ratio",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="신규방문 비중(%)",
                    ),
                ),
                (
                    "monthly_ad_spend",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="CAC·ROAS",
                        null=True,
                        verbose_name="월 광고비(원)",
                    ),
                ),
                (
                    "data_grade",
                    models.CharField(
                        choices=[
                            ("A", "A 연동(POS·플레이스 API)"),
                            ("B", "B 내보내기(엑셀·정산서)"),
                            ("C", "C 수기(사장님 입력)"),
                            ("D", "D 추정(업종평균·모델)"),
                        ],
                        default="C",
                        max_length=1,
                        verbose_name="데이터 등급",
                    ),
                ),
                (
                    "merchant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="acquisition",
                        to="onboarding.merchant",
                        verbose_name="업체",
                    ),
                ),
            ],
            options={
                "verbose_name": "획득 베이스라인",
                "verbose_name_plural": "획득 베이스라인",
            },
        ),
        migrations.CreateModel(
            name="RetentionBaseline",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "revisit_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="[M7] 이탈 5%↓→이익 25~85%↑",
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="재방문율(%)",
                    ),
                ),
                (
                    "regular_ratio",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="단골 비중(%)",
                    ),
                ),
                (
                    "repurchase_cycle_days",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="[M8] RFM",
                        null=True,
                        verbose_name="재구매 주기(일)",
                    ),
                ),
                (
                    "has_membership",
                    models.BooleanField(default=False, verbose_name="멤버십/적립 운영"),
                ),
                (
                    "nps",
                    models.SmallIntegerField(
                        blank=True,
                        help_text="[M9] -100~100",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(-100),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="NPS",
                    ),
                ),
                (
                    "data_grade",
                    models.CharField(
                        choices=[
                            ("A", "A 연동(POS·플레이스 API)"),
                            ("B", "B 내보내기(엑셀·정산서)"),
                            ("C", "C 수기(사장님 입력)"),
                            ("D", "D 추정(업종평균·모델)"),
                        ],
                        default="C",
                        max_length=1,
                        verbose_name="데이터 등급",
                    ),
                ),
                (
                    "merchant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="retention",
                        to="onboarding.merchant",
                        verbose_name="업체",
                    ),
                ),
            ],
            options={
                "verbose_name": "유지 베이스라인",
                "verbose_name_plural": "유지 베이스라인",
            },
        ),
        migrations.CreateModel(
            name="CustomerTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "customer_key",
                    models.CharField(
                        help_text="해시/가명 식별자. 원본 PII 저장 금지.",
                        max_length=64,
                        verbose_name="고객 가명키",
                    ),
                ),
                ("occurred_on", models.DateField(verbose_name="거래일")),
                ("amount", models.PositiveIntegerField(verbose_name="거래금액(원)")),
                (
                    "merchant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="onboarding.merchant",
                        verbose_name="업체",
                    ),
                ),
            ],
            options={
                "verbose_name": "거래로그",
                "verbose_name_plural": "거래로그",
                "ordering": ["-occurred_on"],
                "indexes": [
                    models.Index(
                        fields=["merchant", "customer_key"],
                        name="onboarding__merchan_eaa5bf_idx",
                    ),
                    models.Index(
                        fields=["merchant", "occurred_on"],
                        name="onboarding__merchan_465592_idx",
                    ),
                ],
            },
        ),
    ]
