# Generated by Django 5.2.15 on 2026-06-22 13:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("onboarding", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="merchant",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                help_text="계정별 워크스페이스. 각 사용자는 자기 업체만 조회/수정.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="merchants",
                to=settings.AUTH_USER_MODEL,
                verbose_name="소유 계정",
            ),
        ),
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("user", "사용자"),
                            ("agent", "에이전트"),
                            ("system", "시스템"),
                        ],
                        max_length=8,
                        verbose_name="역할",
                    ),
                ),
                (
                    "persona",
                    models.CharField(
                        blank=True, default="", max_length=8, verbose_name="페르소나"
                    ),
                ),
                ("text", models.TextField(verbose_name="내용")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="작성"),
                ),
                (
                    "merchant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="onboarding.merchant",
                        verbose_name="업체",
                    ),
                ),
            ],
            options={
                "verbose_name": "대화 메시지",
                "verbose_name_plural": "대화 메시지",
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(
                        fields=["merchant", "created_at"],
                        name="onboarding__merchan_17be78_idx",
                    )
                ],
            },
        ),
    ]
