# Generated by Django 5.2.15 on 2026-07-11 04:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("onboarding", "0002_merchant_owner_chatmessage"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeepReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tier",
                    models.CharField(
                        choices=[
                            ("lite", "라이트(플레인 파이프라인)"),
                            ("deep", "딥(핵심 섹션 AB-MCTS 탐색)"),
                        ],
                        default="lite",
                        max_length=8,
                        verbose_name="티어",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "대기"),
                            ("running", "생성 중"),
                            ("done", "완료"),
                            ("failed", "실패"),
                        ],
                        default="pending",
                        max_length=8,
                        verbose_name="상태",
                    ),
                ),
                (
                    "content_md",
                    models.TextField(
                        blank=True, default="", verbose_name="리포트(Markdown)"
                    ),
                ),
                (
                    "meta",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        verbose_name="메타(호출·비용·탐색로그)",
                    ),
                ),
                (
                    "credits_charged",
                    models.PositiveIntegerField(default=0, verbose_name="청구 크레딧"),
                ),
                (
                    "error",
                    models.TextField(blank=True, default="", verbose_name="오류"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="요청"),
                ),
                (
                    "finished_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="완료"),
                ),
                (
                    "merchant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="onboarding.merchant",
                        verbose_name="업체",
                    ),
                ),
            ],
            options={
                "verbose_name": "딥리포트",
                "verbose_name_plural": "딥리포트",
                "ordering": ["-created_at"],
            },
        ),
    ]
