# Generated by Django 5.2.15 on 2026-07-11 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("onboarding", "0003_deepreport"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversionbaseline",
            name="monthly_customers",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="intake v1.1 — 사장님이 아는 숫자. 객단가 자동계산의 분모",
                null=True,
                verbose_name="월 고객수(명)",
            ),
        ),
    ]
