# Generated by Django 5.2.15 on 2026-07-11 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("onboarding", "0004_conversionbaseline_monthly_customers"),
    ]

    operations = [
        migrations.AddField(
            model_name="merchant",
            name="chat_summary",
            field=models.TextField(
                blank=True,
                default="",
                help_text="최근 창 밖의 과거 대화를 저가 모델로 압축한 롤링 요약 — 전체 이력을 매번 보내지 않고도 다음 대화가 과거를 참조.",
                verbose_name="대화 장기기억 요약",
            ),
        ),
        migrations.AddField(
            model_name="merchant",
            name="chat_summary_upto",
            field=models.PositiveIntegerField(
                default=0,
                help_text="이 ID 이하의 메시지는 chat_summary에 병합 완료.",
                verbose_name="요약 반영된 마지막 메시지 ID",
            ),
        ),
    ]
