# Generated by Django 5.2.15 on 2026-07-17 06:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("onboarding", "0005_merchant_chat_summary_merchant_chat_summary_upto"),
    ]

    operations = [
        migrations.CreateModel(
            name="Action",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("persona", models.CharField(max_length=8, verbose_name="담당")),
                ("title", models.CharField(max_length=300, verbose_name="액션 요약")),
                (
                    "detail",
                    models.TextField(blank=True, default="", verbose_name="상세"),
                ),
                (
                    "target_metric",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("avg_rating", "평점"),
                            ("review_count", "리뷰수"),
                            ("place_clicks", "플레이스클릭"),
                            ("aov", "객단가"),
                            ("monthly_customers", "월 고객수"),
                            ("visit_to_purchase_rate", "전환율"),
                            ("revisit_rate", "재방문율"),
                            ("regular_ratio", "단골비중"),
                            ("nps", "NPS"),
                            ("monthly_revenue", "월 매출"),
                        ],
                        default="",
                        max_length=32,
                        verbose_name="타깃 지표",
                    ),
                ),
                (
                    "citations",
                    models.JSONField(
                        blank=True, default=list, verbose_name="근거 인용"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("proposed", "제안됨"),
                            ("active", "실행 중"),
                            ("done", "완료(실측)"),
                            ("dropped", "중단"),
                        ],
                        default="proposed",
                        max_length=10,
                        verbose_name="상태",
                    ),
                ),
                (
                    "baseline_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=14,
                        null=True,
                        verbose_name="시작 시점 값",
                    ),
                ),
                (
                    "result_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=14,
                        null=True,
                        verbose_name="완료 시점 값",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="시작"),
                ),
                (
                    "closed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="마감"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="제안"),
                ),
                (
                    "merchant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actions",
                        to="onboarding.merchant",
                        verbose_name="업체",
                    ),
                ),
            ],
            options={
                "verbose_name": "액션 티켓",
                "verbose_name_plural": "액션 티켓",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["merchant", "status"],
                        name="onboarding__merchan_ca0da2_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="KpiSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "metric",
                    models.CharField(
                        choices=[
                            ("avg_rating", "평점"),
                            ("review_count", "리뷰수"),
                            ("place_clicks", "플레이스클릭"),
                            ("aov", "객단가"),
                            ("monthly_customers", "월 고객수"),
                            ("visit_to_purchase_rate", "전환율"),
                            ("revisit_rate", "재방문율"),
                            ("regular_ratio", "단골비중"),
                            ("nps", "NPS"),
                            ("monthly_revenue", "월 매출"),
                        ],
                        max_length=32,
                        verbose_name="지표",
                    ),
                ),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=2, max_digits=14, verbose_name="값"
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        default="chat", max_length=12, verbose_name="출처"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="측정"),
                ),
                (
                    "merchant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="snapshots",
                        to="onboarding.merchant",
                        verbose_name="업체",
                    ),
                ),
            ],
            options={
                "verbose_name": "KPI 스냅샷",
                "verbose_name_plural": "KPI 스냅샷",
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(
                        fields=["merchant", "metric", "created_at"],
                        name="onboarding__merchan_f83635_idx",
                    )
                ],
            },
        ),
    ]
