# Generated by Django 5.2.15 on 2026-07-17 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("onboarding", "0006_action_kpisnapshot"),
    ]

    operations = [
        migrations.AddField(
            model_name="action",
            name="protocol",
            field=models.CharField(
                choices=[("simple", "전후 비교"), ("abab", "격주 on-off 교차")],
                default="simple",
                help_text="abab=격주로 실행/중단을 교차해 국면 평균을 비교(계절성·추세에 강함)",
                max_length=8,
                verbose_name="검증 프로토콜",
            ),
        ),
    ]
