# Generated by Django 5.2.16 on 2026-08-03 08:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("onboarding", "0007_action_protocol"),
    ]

    operations = [
        migrations.AddField(
            model_name="merchant",
            name="variable_cost_ratio",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                help_text="매출에 비례하는 비용 비율(재료비+카드/배달 수수료 등). 이 값이 있어야 '증분 공헌이익'을 잰다 — 없으면 매출만 재게 되어 할인 조언이 마진을 깎아도 '성공'으로 보인다.",
                max_digits=4,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name="변동비율(%)",
            ),
        ),
        migrations.AlterField(
            model_name="action",
            name="target_metric",
            field=models.CharField(
                blank=True,
                choices=[
                    ("avg_rating", "평점"),
                    ("review_count", "리뷰수"),
                    ("place_clicks", "플레이스클릭"),
                    ("aov", "객단가"),
                    ("monthly_customers", "월 고객수"),
                    ("visit_to_purchase_rate", "전환율"),
                    ("revisit_rate", "재방문율"),
                    ("regular_ratio", "단골비중"),
                    ("nps", "NPS"),
                    ("monthly_revenue", "월 매출"),
                    ("contribution_margin", "월 공헌이익"),
                    ("unit_contribution_margin", "주문당 공헌이익"),
                    ("variable_cost_ratio", "변동비율"),
                ],
                default="",
                max_length=32,
                verbose_name="타깃 지표",
            ),
        ),
        migrations.AlterField(
            model_name="kpisnapshot",
            name="metric",
            field=models.CharField(
                choices=[
                    ("avg_rating", "평점"),
                    ("review_count", "리뷰수"),
                    ("place_clicks", "플레이스클릭"),
                    ("aov", "객단가"),
                    ("monthly_customers", "월 고객수"),
                    ("visit_to_purchase_rate", "전환율"),
                    ("revisit_rate", "재방문율"),
                    ("regular_ratio", "단골비중"),
                    ("nps", "NPS"),
                    ("monthly_revenue", "월 매출"),
                    ("contribution_margin", "월 공헌이익"),
                    ("unit_contribution_margin", "주문당 공헌이익"),
                    ("variable_cost_ratio", "변동비율"),
                ],
                max_length=32,
                verbose_name="지표",
            ),
        ),
    ]
